mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    mem_limit: 512m
    environment:
      - CONSUL=consul
    links:
      - consul:consul
    ports:
      - 3306

consul:
    extends:
      file: docker-compose.yml
      service: consul
    ports:
    - 8500:8500
