mysql:
    extends:
      file: common-compose.yml
      service: mysql
    mem_limit: 512m
    build: .
    links:
      - consul:consul
    ports:
      - 3306

mysql_replica:
    extends:
      file: common-compose.yml
      service: mysql
    mem_limit: 512m
    build: .
    environment:
      - CONTAINERBUDDY=file:///etc/containerbuddy-replica.json
    links:
      - consul:consul
    ports:
      - 3306

consul:
    extends:
      file: common-compose.yml
      service: consul
    ports:
    - 8500:8500
