mysql:
    extends:
      file: common-compose.yml
      service: mysql
    mem_limit: 512m
    build: .
    #volumes:
    #  - ~/src/tgross/triton-mysql/tmp/backup:/tmp/backup
    links:
      - consul:consul
    ports:
      - 3306

consul:
    extends:
      file: common-compose.yml
      service: consul
    ports:
    - 8500:8500
