version: '2.1'

services:
  mysql:
    image: autopilotpattern/mysql:${TAG:-latest}
    mem_limit: 512m
    restart: always
    expose:
      - 3306
    env_file: _env
    network_mode: bridge
    environment:
      - CONSUL_AGENT=1
      - LOG_LEVEL=DEBUG
      - CONSUL=consul
    links:
      - consul:consul

  consul:
    image: consul:0.7.1
    command: >
      agent -server -client=0.0.0.0 -bootstrap -ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    network_mode: bridge
    dns:
      - 127.0.0.1
